### ISSUE TITLE
Can we create a group dialog with 2 members and Add new members successively?

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#104]
Like initialise with 2 members. And new members get added to the same dialog with time. Is this possible ?

**Comment by jddeep** [comment]
@TatankaConCube please have a look here

**Comment by jddeep** [comment]
@DaveLomber @CubeRomanMagellan @ccvlad any leads ?

**Comment by TatankaConCube** [comment]
@jddeep sure you can create the group dialog with two members and then add the occupants when you want. In current realization, this case (for creation group chats with three or more users) was made just as an example.

**Comment by TatankaConCube** [comment]
the requested functionality is already realized in this app, just follow the [code](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/ChatDialogDetailsActivity.kt#L276)

**Comment by CubeRomanMagellan** [comment]
no long-term activity
