### ISSUE TITLE
Android 10 ,11, and above 

### ISSUE THREAD

**Issue by tayyabalibasra** [ConnectyCube/android-messenger-app#105]
hi i am using your sample code for call application but below android 10 background call is working fine but in android 10 and above background call not showing calling screen plz suggest me what piece of code i am missing plz reply me with valuable solution as soon possible

**Comment by TatankaConCube** [comment]
you can use the Notification with the full-screen activity. A similar logic was realized in our '[connectycube-flutter-call-kit](https://github.com/ConnectyCube/connectycube-flutter-call-kit/blob/master/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/NotificationsManager.kt#L28)'. You can use it as an example for implementation required feature.

**Comment by tayyabalibasra** [comment]
sir can i used this call in native android

**Comment by TatankaConCube** [comment]
unfortunately no, but you can use the code from it in your native Android app

**Comment by tayyabalibasra** [comment]
but how can we use flutter plugin in native android app plz can you explain

**Comment by TatankaConCube** [comment]
I meant the **CODE** from the plugin, not the **FLUTTER PLUGIN**. This code is written on the Kotlin and you can copy/paste it to your project.

**Comment by tayyabalibasra** [comment]
but incoming call session how can we get

**Comment by TatankaConCube** [comment]
you will show it from the push notification. you can put any data to the push notification

**Comment by tayyabalibasra** [comment]
How can we get incoming call session

**Comment by tayyabalibasra** [comment]
FirebaseMessagingService: Message Received From Firebase: {notification_type=95a7dcf8-70b7-4206-a4b5-36f2e830eb8c, push_notification_type=2, message=You have got new Incoming Call. Open app to manage it, answer_timeout=60}

Hi sir basically firebase messging service provide this data only 
but in call kitt of flultter 
  callId,
        callType,
        callInitiatorId,
        callInitiatorName,
        callOpponents,
        userInfo
        i did not have this information in firebase messging service so how can i reject call etc without these detail 
Plz guide me as soon as posible

**Comment by TatankaConCube** [comment]
if you see the code more carefully you will see that the caller sends the push notification for all call members [here](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/helpers/RTCSessionManager.kt#L88) and there you can put any data to the push notification

**Comment by tayyabalibasra** [comment]
hi sir i have question in your sdk have a asset file which contain static users list
 but i did not use this file but i want to fetch all users which api you recomended i already use getuserbyNumber(),getUserbyemail(),getUserById() but these api did not return all user how can i get all user can you explain

**Comment by TatankaConCube** [comment]
@tayyabalibasra last question not related to the initial, please create a new ticket and close current if your issue was resolved

**Comment by tayyabalibasra** [comment]
Great service
