### ISSUE TITLE
User Issue

### ISSUE THREAD

**Issue by tayyabalibasra** [ConnectyCube/android-messenger-app#106]
hi sir i have question in your sdk have a asset file which contain static users list
but i did not use this file but i want to fetch all users which api you recomended i already use getuserbyNumber(),getUserbyemail(),getUserById() but these api did not return all user how can i get all user can you explain

**Comment by TatankaConCube** [comment]
you can use this snippet for getting all users with pagination, the maximum number of items per page is 100.
```dart
GetUsersQuery.byFilter(null, null, {'page': 1, 'per_page': 10})
    .perform()
    .then((cubeUser) {

    }).catchError((onError) {

    });
```

**Comment by TatankaConCube** [comment]
sorry, I provided example for Flutter))) will update soon

**Comment by tayyabalibasra** [comment]
ok waiting

**Comment by TatankaConCube** [comment]
there example on the Kotlin:
```kotlin
        val pagedRequestBuilder = PagedRequestBuilder().apply {
            page = 1
            perPage = 50
        }
        ConnectycubeUsers.getUsers(pagedRequestBuilder).performAsync(object :
            EntityCallback<ArrayList<ConnectycubeUser>> {
            override fun onSuccess(users: ArrayList<ConnectycubeUser>, args: Bundle) {

            }

            override fun onError(error: ResponseException) {

            }
        })
```

**Comment by tayyabalibasra** [comment]
ok thanks

**Comment by TatankaConCube** [comment]
please check and close the ticket if your issue was resolved

**Comment by tayyabalibasra** [comment]
great bro
