### ISSUE TITLE
base You don't have appropriate permissions to perform this operation

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#109]
Can't add users to a group chat @TatankaConCube

**Comment by jddeep** [comment]
`com.connectycube.core.exception.ResponseException: base You don't have appropriate permissions to perform this operation`

Receiving this error @TatankaConCube @DaveLomber please take a look

**Comment by CubeRomanMagellan** [comment]
no long-term activity, closed
