### ISSUE TITLE
Call Ringing Status 

### ISSUE THREAD

**Issue by tayyabalibasra** [ConnectyCube/android-messenger-app#110]
Hi sir can you guide me about Ringing status of call  currently i used this but i can not find(Ringing,Calling,Held,Contected) Status in this status if i want  set static  these status can you guide me plz as soon as possible
/**
 * Called each time when new session request is received.
 */
override fun onReceiveNewSession(session: RTCSession) {}

/**
 * Called in case when user didn't answer within timer expiration period
 */
override fun onUserNotAnswer(session: RTCSession, userId: Int) {}

/**
 * Called in case when opponent has rejected your call
 */
override fun onCallRejectByUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}

/**
 * Called in case when opponent has accepted your call
 */
override fun onCallAcceptByUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}

/**
 * Called in case when opponent hung up
 */
override fun onReceiveHangUpFromUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}

/**
 * Called in case when user didn't make any actions on received session
 */
override fun onUserNoActions(session: RTCSession, userId: Int) {}

/**
 * Called in case when session will close
 */
override fun onSessionStartClose(session: RTCSession) {}

/**
 * Called when session is closed.
 */
override fun onSessionClosed(session: RTCSession?) {}

**Comment by Rehachoudhary0** [comment]
Hi @TatankaConCube, Kindly help

**Comment by tayyabalibasra** [comment]
???????

**Comment by tayyabalibasra** [comment]
?????

**Comment by Rehachoudhary0** [comment]
hey thank you so much for reply .... we are suffering since few week we are
using sample sdk for calling app and we are trying to modify same things
like we are trying to implement heads up calling notification with two
button first answer second reject on that buttons we can able to
perform action getting user id null error kindly please help on it

**Comment by tayyabalibasra** [comment]
???????

**Comment by Rehachoudhary0** [comment]
i dont think so its need too much time . i just added the button in pop
notification answer and rejection .want to action perform need help on it
..please provide the technical team for that we want to implement this in
our company project .

**Comment by Rehachoudhary0** [comment]
This is not update in SDK this is only firebase ui popup notification  like
this ..


[image: 2edd1c3c-aa9d-4776-b537-5723911d0958.png]

**Comment by tayyabalibasra** [comment]
image not showing

**Comment by tayyabalibasra** [comment]
i want action functionality  reject and answer and when app is kill  or  background  during call no notification show of end call etc

**Comment by CubeRomanMagellan** [comment]
no long-term activity
