### ISSUE TITLE
Issue is a tech one heads Up 

### ISSUE THREAD

**Issue by Rehachoudhary0** [ConnectyCube/android-messenger-app#111]
Hello Team,
 thank you so much for reply on mail  we are suffering since few week we are using sample SDK for calling app and we are trying to modify same things like we are trying to implement heads up calling notification with two button first answer second reject on that buttons we can able to perform action getting user id null 
![image](https://user-images.githubusercontent.com/85510636/157235021-bddb59ed-4ea4-4e7f-a597-018649a2ebd6.png)
error kindly please help on it

**Comment by TatankaConCube** [comment]
answered [here](https://github.com/ConnectyCube/android-messenger-app/issues/112)
