### ISSUE TITLE
calling screen open when app is killed mode?

### ISSUE THREAD

**Issue by Rehachoudhary0** [ConnectyCube/android-messenger-app#112]
one more thing to need to clear when app is killed mode then calling notification is coming app is not showing calling screen .when i add overlay permission on it the showing screen on killing mode ... but we want this action without runtime permission . please help us to over come to this problem .

**Comment by Rehachoudhary0** [comment]
hey where i will use the class for headup notification . we get pending intent in AppNotificationManager class. how to take this class from where what is the path for calling ?

**Comment by Rehachoudhary0** [comment]
hey where i will use the class of given by you .since am using AppNotificationManager class for pending intent .where i will located this class please tell me . according to project structure .

**Comment by CubeRomanMagellan** [comment]
no long-term activity, closed
