### ISSUE TITLE
App doesnt work in latest version.

### ISSUE THREAD

**Issue by AnuraagKotnala** [ConnectyCube/android-messenger-app#114]
Pom files arent downloading, documentation is not updated.

**Comment by CubeRomanMagellan** [comment]
Hello @AnuraagKotnala, android-messenger-app will be updated in the future (can't say when exactly). But it's not very difficult to update it by yourself with new SDK [docs](https://developers.connectycube.com/android/?id=connect-sdk).

**Comment by CubeRomanMagellan** [comment]
For now android-messenger-app is updated and works as expected.
