### ISSUE TITLE
Could not find org.webrtc:google-webrtc:1.0.24180.      Required by:          project :app > com.connectycube:connectycube-android-sdk-videochat:1.9.2

### ISSUE THREAD

**Issue by Ravi-V2R** [ConnectyCube/android-messenger-app#120]
In my application I am using connectycube videochat sdk but facing an issue, any help will really helpfull

 implementation "com.connectycube:connectycube-android-sdk-chat:1.9.2"
 implementation "com.connectycube:connectycube-android-sdk-storage:1.9.2"
 implementation "com.connectycube:connectycube-android-sdk-pushnotifications:1.9.2"
 implementation "com.connectycube:connectycube-android-sdk-videochat:1.9.2"
 
 in app level gradle
  maven {
            url "https://github.com/ConnectyCube/connectycube-android-sdk-releases/raw/master/"
        }
        
  It sync app properly but while running it shows error
  
  Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find org.webrtc:google-webrtc:1.0.24180.
     Required by:
         project :app > com.connectycube:connectycube-android-sdk-videochat:1.9.2
         
         
         
         Here is my app level gradle file
         
 
// Top-level build file where you can add configurationewTextn options common to all sub-projects/modules.
buildscript {
    ext {
        kotlinVersion = "1.8.0"
    }
    repositories {
        google()
        jcenter()
        maven { url "https://jcenter.bintray.com" }
        maven {
            url 'https://jitpack.io'
        }
        mavenCentral()
//        gradlePluginPortal()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20'
        classpath 'com.google.gms:google-services:4.4.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

}

allprojects {

    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jcenter.bintray.com" }
//        gradlePluginPortal()

        maven {
            url 'https://jitpack.io'
        }
        maven { url "https://connectycube.com/maven" }
        maven {
            url "https://github.com/ConnectyCube/connectycube-android-sdk-releases/raw/master/"
        }

        maven {
            url("$rootDir/..")
        }
        maven {
            url 'https://maven.google.com'
        }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
ext {
    chatAdapterVersion = '1.0.2'
}

Checked in other system too below library is causing issue
implementation "com.connectycube:connectycube-android-sdk-videochat:1.9.2"

If this library is commented out it works

Thanks in advance

**Comment by CubeRomanMagellan** [comment]
Hi @Ravi-V2R !
The _org.webrtc:google-webrtc:1.0.24180_ library is no longer available on maven. But you can add it locally to your project. For ex. add _google-webrtc-1.0.24180.aar_ and _google-webrtc-1.0.24180.pom_ files in local maven (for Linux and Mac ~/.m2). 

Don't forget to add mavenLocal() in project build.gradle. 

But I strongly recommend use _SDK v2._

**Comment by yash-dadhich** [comment]
[CubeRomanMagellan](https://github.com/CubeRomanMagellan) 
Thanks for your support this worked for me.
