### ISSUE TITLE
[question] possibly open call activity directly when receiving new call?

### ISSUE THREAD

**Issue by mamzii** [ConnectyCube/android-messenger-app#42]

**Comment by TatankaConCube** [comment]
Hello @mamzii thank you for your question. Yes, you can do it. As a possible solution you can create service which will save chat connection (like [ChatConnectionManager.kt](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/ChatConnectionManager.kt)). Then after receive call push-notification you will start this service and initialize [RTCSessionManager](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/ChatConnectionManager.kt#L89). RTCSessionManager starts listen calls and after receive new call will open [CallActivity.kt](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/CallActivity.kt)

**Comment by TatankaConCube** [comment]
feel free to open other questions if you have
