### ISSUE TITLE
App close 

### ISSUE THREAD

**Issue by InfoAndroid** [ConnectyCube/android-messenger-app#44]
If I receive a  call and we press back button go on chat screen after that I call back the same user app was getting a crash.
Q.How we can handle this?

**Comment by TatankaConCube** [comment]
@InfoAndroid please, add more information about your issue. We need at least logs to understand you issue. For better understanding of how calls work please learn our [documentation](https://developers.connectycube.com/android/videocalling).

**Comment by TatankaConCube** [comment]
Closed. No response received for a long time.
