### ISSUE TITLE
Receiving call from iOS when Android is in background, doesn't work.

### ISSUE THREAD

**Issue by mwaked** [ConnectyCube/android-messenger-app#51]
I made a call from iOS and Android app is in background, `ReceiveNewSession` doesn't work..
it works when android calls android.

Here's the code:

```
class CallService : IntentService("CallService") {

    override fun onStartCommand(intent: Intent, flags: Int, startId: Int): Int {
        Logger.d(CALL_TAG, "CallService is started")

        isRunning = true

        getBundleData(intent)

        startForeground(NOTIFICATION_REQUEST_CODE, if (isIncomingCall)
            incomingCallNotification(appointmentData, isIncomingCall)
        else callNotification(appointmentData, isIncomingCall))

        initConnectyCube()

        return Service.START_NOT_STICKY
    }
}
```

**Comment by TatankaConCube** [comment]
we didn't test our new **messenger-app** with iOS samples. For your case try check next

- you added all needed parameters to push notification on iOS side;
- your push notification was successfully created, you can check it in ConnectyCube admin panel https://admin.connectycube.com/apps/**appId**/service/push-notifications/queue;
- android user successfully subscribed on push notifications;
- android user successfully receive push notification (was triggered method [onMessageReceived](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/fcm/PushListenerService.kt#L10));

**Comment by mwaked** [comment]
@TatankaConCube I tried all of these and it's work fine between android devices but not work between Android and Ios, pleas can you test android messenger-app with Ios and try to make call from Ios to android when android in background to check this issue with ConnectyCube Ios team.

Thanks

**Comment by mwaked** [comment]
@TatankaConCube I tried all of these and it's work fine between android devices but not work between Android and Ios, pleas can you test android messenger-app with Ios and try to make call from Ios to android when android in background to check this issue with ConnectyCube Ios team.

Thanks

**Comment by TatankaConCube** [comment]
I can help only with android side, sorry. 
Did you receive push notification on android side? 
Calls between iOS - iOS work correctly?

**Comment by iamimsh** [comment]
Call from iOS to iOS doesn't work.
Also calls from iOS to Android doesn't work.

Calls from Android to iOS works fine and also from Android to Android.

But, if the SDK isn't compatible with multiple platforms, or at least between iOS and Android, then there's no point in using this SDK.

**Comment by TatankaConCube** [comment]
Android and iOS SDKs are fully compatible. I think you should fix call on iOS side (between iOS-iOS) then start testing cross platform cases. Looks like you don't start call on iOS side. To better understanding your issue, please provide us log from android side during make call from iOS.

**Comment by krishna11124** [comment]
Hi Is there any Hint About Receive Call-In Background In Android Or Ios??

**Comment by TatankaConCube** [comment]
@krishna11124  wich functionality do you need? If you need just background calls, you can use the Push notifications feature from our SDK. For iOS, you can use APNS_VOIP or showing a Call kit. This ticket closed, please create a new one and describe your problem.

**Comment by krishna11124** [comment]
I Need To Get Background Calls In Android Or Ios Plateform ...And I Can't
Understand in Your Blog ...How To Implement It, IS There Any Source Or
Source Link About It.Thanks

**Comment by TatankaConCube** [comment]
There oriented steps for implementing this feature:
1) caller sends push notification for all opponents with needed call data (use universal pushes for it with parameter `ios_voip=1`);
2) after receiving push notification on the opponent's side you can:
- for iOS - show CallKit and by action start chat connection and send need signal (accept or reject) and show call screen if need;
- for Android - start service, which will connect to the chat and show Call notification and/or Incoming call screen, then by clicking on action open Call screen if need; 

We realized similar logic in our sample, but instead of showing the Incoming call screen we just show the notification.

**Comment by krishna11124** [comment]
Hlow  team actually I want to create a tap to return a call feture in app
.So When I go back from calling it will not notify in app the call is
running or not.so I want to create service like if I go back from calling
screen then it's will so me tap to return a call below my app header..like
whatsapp If ur developer team support me please feel free to calling or
whatsapp +918979720606...R u getting.this??Thanks

**Comment by TatankaConCube** [comment]
This functionality completely depends on your needs. For Android, you can use Notification for example. For iOS you can use another solution. Requested functionality not related to Connectycube Flutter SDK or sample. Need to investigate, which features from the Flutter framework will help you to realize the required functionality.
