### ISSUE TITLE
Error in Build

### ISSUE THREAD

**Issue by XenSpa** [ConnectyCube/android-messenger-app#55]
When I try to build the app for APK in Android Studio I am getting this error:

app/src/main/java/com/conntectybube/messenger/ChatMessageActivity.kt   (2 errors)
-The boolean literal does not conform to the expected type ExtendedFloatingActionButton.OnChangedCallback
-The boolean literal does not conform to the expected type ExtendedFloatingActionButton.OnChangedCallback

And it "jumps" to those two:
messages_recycleview.addOnScrollListener(object : RecyclerView.OnScrollListener() {
            fun shrinkFab() {
                scroll_fb.iconGravity = ICON_GRAVITY_START
                scroll_fb.shrink()
     -->      scroll_fb.hide(false)
                scroll_fb.text = ""

  if (totalItemCount > 0 && shouldShow) {
                 if (!scroll_fb.isShown) {
           -->       scroll_fb.show(false)
                        scroll_fb.alpha = 0.3f

**Comment by TatankaConCube** [comment]
@XenSpa  please add more details how you build app. Did you just clone app in Android Studio and try to build? Or you added our code to your exist app and try build? Please add here full build log with all errors. You can use [gist](https://gist.github.com/) to share logs.

**Comment by XenSpa** [comment]
I have import the project again and now it works. The first time that I have imported it I had the above error. I have imported the whole project with Android Studio and then, after I have made the changes with users and passwords according to instruction, I have tried to build it.
