### ISSUE TITLE
No audio in video call when audiodevice set to speakerphone

### ISSUE THREAD

**Issue by payalgoyal** [ConnectyCube/android-messenger-app#58]
I have used the sample code but on making video call, opponent video is seen but there is no audio when audiodevice is set to speaker phone, whereas, when plugging headphone, audio is present

**Comment by TatankaConCube** [comment]
hello @payalgoyal thank you for your question, but we need more information about your issue. Please add detailed steps to reproduce this issue, full logs from both devices (caller and receiver), devices specifications which you use to tests and other useful information for investigating your issue. Today I tried to reproduce your issue on Pocophone F1, Samsung Galaxy A7, Samsung s10 but unfortunately unsuccessful.

**Comment by TatankaConCube** [comment]
@payalgoyal maybe you just have very quiet volume of audio stream of your opponent? For checking this case you can use new feature from our SDK (since version 1.9.1) - change volume of audio stream. For it use next code:

```java
RTCSession session; //some call session
int userId = 12345; //some opponent ID
RTCMediaStreamManager mediaStreamManager = session.getMediaStreamManager();
RTCAudioTrack audioTrack = mediaStreamManager.getAudioTrack(userId);
audioTrack.setVolume(10); //volume level from 0 to 10
```

**Comment by payalgoyal** [comment]
I have setvolume as suggested in onConnectedToUser method of
VideoConversationFragment. Still volume is not increased when audio device
is Speaker_Phone.

**Comment by payalgoyal** [comment]
This issue is solved. Permission for modify_audio_settings solved the
issue. But there is lot of noise and echo in the audio. How can this be
avoided?

**Comment by TatankaConCube** [comment]
@payalgoyal please create new issue with your problem with noise and echo in the audio. Please add more information about this issue: detailed steps to reproduce, info about devices, logs etc.
