### ISSUE TITLE
Noise and echo during video call

### ISSUE THREAD

**Issue by payalgoyal** [ConnectyCube/android-messenger-app#60]
While making call from one device to another, as the receiver receives the call, there is lot of noise, and echo.

Device Used:
1. Samsung A30 (Android Version 9)
2. Samsung SM-J6 (Android Version 8)

Attached are the callActivity and videoConversation fragment
[callActivity.txt](https://github.com/ConnectyCube/android-messenger-app/files/4770508/callActivity.txt)
[VideoConversationFragment.txt](https://github.com/ConnectyCube/android-messenger-app/files/4770509/VideoConversationFragment.txt)

**Comment by payalgoyal** [comment]
Any suggestion for the issue?

**Comment by krunaldarji** [comment]
@TatankaConCube  Do we have any solution for flutter SDK?
