### ISSUE TITLE
Empty screen ChatMessageActivity when open by new way

### ISSUE THREAD

**Issue by nguyenbahung94** [ConnectyCube/android-messenger-app#61]
Hi, I want to login by these steps and base on your example.

1. I replace method login in LoginActivity by this:

 var user1 = ConnectycubeUser()
        user1.login = "hung1"
        user1.password = "password1"

        ConnectycubeUsers.signIn(user1).performAsync(object : EntityCallback<ConnectycubeUser> {
            override fun onSuccess(p0: ConnectycubeUser?, p1: Bundle?) {
                p0!!.password = user1.password
                Toast.makeText(this@LoginActivity, "user 1 login success", Toast.LENGTH_SHORT)
                    .show()
                SharedPreferencesManager.getInstance(this@LoginActivity).saveCurrentUser(p0!!)
                createChatPrivate(1479875)
            }

            override fun onError(p0: ResponseException?) {
                Toast.makeText(this@LoginActivity, p0?.message.toString(), Toast.LENGTH_SHORT)
                    .show()
            }

        })

//////////////////////
  private fun createChatPrivate(id: Int) {
        val occupantIds = ArrayList<Int>()
        occupantIds.add(id)

        val dialog = ConnectycubeChatDialog().apply {
            type = ConnectycubeDialogType.PRIVATE
            setOccupantsIds(occupantIds)
        }

        ConnectycubeRestChatService.createChatDialog(dialog)
            .performAsync(object : EntityCallback<ConnectycubeChatDialog> {
                override fun onSuccess(createdDialog: ConnectycubeChatDialog, params: Bundle) {
                    startChatActivity(createdDialog)
                }

                override fun onError(exception: ResponseException) {

                }
            })
    }
//////////
   private fun startChatActivity(chat: ConnectycubeChatDialog) {
        val intent = Intent(this@LoginActivity, ChatMessageActivity::class.java)
        intent.putExtra(EXTRA_CHAT, chat)
        startActivity(intent)
    }
2. after login success I will create a private chat and then open ChatMessageActivity .
then I get issue empty screen with a message "Something went wrong, try again later"

You should uninstall the app before test this.
I got an issue for a few days and I hope you can help me fix this.
Thanks,

**Comment by TatankaConCube** [comment]
Please provide  full log from logcat and add more information on which step you get this error (login to the chat or load messages or another ways).

**Comment by nguyenbahung94** [comment]
> Please provide full log from logcat and add more information on which step you get this error (login to the chat or load messages or another ways).

**Comment by TatankaConCube** [comment]
in logs I found next line 'Caused by: kotlin.UninitializedPropertyAccessException: lateinit property modelMessageSender has not been initialized'. Please check if you initialise field `modelMessageSender` in your `ChatMessageActivity` class before send message.

**Comment by nguyenbahung94** [comment]
> in logs I found next line 'Caused by: kotlin.UninitializedPropertyAccessException: lateinit property modelMessageSender has not been initialized'. Please check if you initialise field `modelMessageSender` in your `ChatMessageActivity` class before send message.

1, I see, But I want to know why the input when start ChatMessageActivity is an instance of ConnectycubeChatDialog, then  I pass that object but the code did not work well as your example.

2. There are two ways to start ChatMessageActivity 
 - The first case is I click on the item of screen ChatDialogActivity then open ChatMessageActivity. it's oke, the message synchronized.
- The second case I create an instance of ConnectycubeChatDialog then pass it into ChatMessageActivity. it's not work well, the message not synchronizes. I still receive the message but it does not have two icons check blue at the bottom of the message.

How I can fix this? I want to use it to make a real app.
I really need solution for these case, Could you answer me soon?

**Comment by TatankaConCube** [comment]
We need FULL log to investigate behavoir of your app logic. I asked this information in my previous comments, but you provided only stacktrace of error. From provided information we can't understand did you send message or not, did sender receive message status package or not, etc. I think this issue related with your new logic, but without asked information we can't help you.

**Comment by nguyenbahung94** [comment]
> We need FULL log to investigate behavoir of your app logic. I asked this information in my previous comments, but you provided only stacktrace of error. From provided information we can't understand did you send message or not, did sender receive message status package or not, etc. I think this issue related with your new logic, but without asked information we can't help you.


Can you check out this link: https://drive.google.com/file/d/1LdRHn5XIglWWiCncCi9bYMQSa-V8MUBS/view?usp=sharing
Please download the project and run, When you login with different user (I already set two user in the project) and chat you will understand. Thank you for your response to me soon.

**Comment by TatankaConCube** [comment]
today I built your app and tested. After first start of app behavior looks like normal, but when I clicked back button I receive behavoir like you described before. After fast review your code I found next part

```kotlin
        ConnectycubeRestChatService.createChatDialog(dialog)
            .performAsync(object : EntityCallback<ConnectycubeChatDialog> {
                override fun onSuccess(createdDialog: ConnectycubeChatDialog, params: Bundle) {
                    // startChatActivity(createdDialog)
                    chatDialogListViewModel.createNewChatDialog(createdDialog)
```

why you call `chatDialogListViewModel.createNewChatDialog` in success block of request `ConnectycubeRestChatService.createChatDialog`? As result you call same request again, because method `chatDialogListViewModel.createNewChatDialog` calls `ConnectycubeRestChatService.createChatDialog` inside.  

If you see logs, you will found new request for dialog creation with next parameters:
```
        name=null
        occupants_ids=1479801,1479875
        type=3
```
I result you get new dialog with name 'null'. Then you asked messages for this dialog and receive empty list, it is expected behavior, because you don't have any messages in new dialog.

Please review your code and fix not clear behavior of your app .

**Comment by nguyenbahung94** [comment]
> today I built your app and tested. After first start of app behavior looks like normal, but when I clicked back button I receive behavoir like you described before. After fast review your code I found next part
> 
> ```kotlin
>         ConnectycubeRestChatService.createChatDialog(dialog)
>             .performAsync(object : EntityCallback<ConnectycubeChatDialog> {
>                 override fun onSuccess(createdDialog: ConnectycubeChatDialog, params: Bundle) {
>                     // startChatActivity(createdDialog)
>                     chatDialogListViewModel.createNewChatDialog(createdDialog)
> ```
> 
> why you call `chatDialogListViewModel.createNewChatDialog` in success block of request `ConnectycubeRestChatService.createChatDialog`? As result you call same request again, because method `chatDialogListViewModel.createNewChatDialog` calls `ConnectycubeRestChatService.createChatDialog` inside.
> 
> If you see logs, you will found new request for dialog creation with next parameters:
> 
> ```
>         name=null
>         occupants_ids=1479801,1479875
>         type=3
> ```
> 
> As result you get new dialog with name 'null'. Then you asked messages for this dialog and receive empty list, it is expected behavior, because you don't have any messages in new dialog.
> 
> Please review your code and fix not clear behavior of your app .

I was my bad I'm so sorry about that.
I was check and write new code to make it more clear about my issue.
Please help me check out this link : https://drive.google.com/file/d/1z8MIiRLtEZKgXOhGop3o_tDvM10VjHGS/view?usp=sharing

When you run a project you will get a message "Error while loading users" But don't pay attention to that.
The issue I was mentioned here is the message I sent it not synchronized.
When I reinstall and log in again the message synchronized, like the first message in the picture below.

![isssue 1](https://user-images.githubusercontent.com/17875845/85821544-13534d00-b7a3-11ea-905f-1c79cb71c99a.jpg)
![issue 2](https://user-images.githubusercontent.com/17875845/85821550-16e6d400-b7a3-11ea-91d3-90c70abd1b60.jpg)

**Comment by TatankaConCube** [comment]
now I can't reproduce issue from yesterday, what help you need now?

**Comment by nguyenbahung94** [comment]
> now I can't reproduce issue from yesterday, what help you need now?

Like I said before the I still receive the message but it does not have two icons check blue at the bottom of the message. When I'm chatting, Could you try function chat on two devices, you will more understanding.
I run the app on two devices at the same time and chat but the message still not have two blue sticks at the bottom of the message. Like the picture below
![issue 2](https://user-images.githubusercontent.com/17875845/85846012-6216dc00-b7cf-11ea-8db7-718819f91496.jpg)

**Comment by TatankaConCube** [comment]
As you can see in our sample `ChatMessagesStatusListener` initialises in `ChatDialogActivity`, but in your code you don't use this activity, it is because you don't get statuses of messages. You can move needed logic from `ChatDialogActivity` to `ChatMessageActivity` but pay attention what and how you do in your code.

**Comment by nguyenbahung94** [comment]
> As you can see in our sample `ChatMessagesStatusListener` initialises in `ChatDialogActivity`, but in your code you don't use this activity, it is because you don't get statuses of messages. You can move needed logic from `ChatDialogActivity` to `ChatMessageActivity` but pay attention what and how you do in your code.

Finally, I'm done with this issue, Thank you for spending time to support me.
Thank you so much and Have a nice day,
