### ISSUE TITLE
Leaving group deletes the group dialog from dialog list

### ISSUE THREAD

**Issue by payalgoyal** [ConnectyCube/android-messenger-app#62]
I am developing chat app, which contain 1-1 messaging and group chat. When a user leaves the group, group dialog is removed from the dialog list. 

I want to get the group dialog with the messages till the time, user leaves the group as in whatsapp.

Is there a way to keep the dialog in the list with messages till the time user leaves the group?

**Comment by TatankaConCube** [comment]
Please add more details what functionality you need. Do you want leave dialog in list but without possibility to write here? What expected behavior with this dialog you need after reinstall app and relogin user? Or you need another functionality?

**Comment by payalgoyal** [comment]
I want the dialog to exist in list with the message history, till user left the group. He should be avle to see past messages that were send before leaving group. But he should not be allowed to message further to that group or receive message from that group

**Comment by TatankaConCube** [comment]
For it you can mark this dialog as 'archived' locally. Then disable push notifications for dialog using [this docs](https://developers.connectycube.com/android/messaging?id=chat-notifications-settings). In messages listener you can ignore messages for this dialog and skip loading of new messages for this dialog after oppening it.

**Comment by payalgoyal** [comment]
How can I archive locally? I have no idea on this

**Comment by TatankaConCube** [comment]
It depends on your preferences, you can add field to local DB or add field in Shared preferences to store ids of 'archived' dialogs. Or if you need this information after relogin user, you can store list of ids of 'archived' dialog to user's 'customData' field.
