### ISSUE TITLE
Android- empty dialogs list

### ISSUE THREAD

**Issue by andrewsafwatsamuel** [ConnectyCube/android-messenger-app#65]
Androidp-When retrieve dialogs dialogs count return correctly but the dialogs array returns empty

![empty chat list](https://user-images.githubusercontent.com/34843386/86843976-a0ea4300-c0a7-11ea-890f-db63a5ed66c6.png)

**Comment by TatankaConCube** [comment]
hello @andrewsafwatsamuel, sorry for the long time answer. Can you reproduce this issue on our sample app? Please provide us a full log with request and response from ConnectyCube server. In your code snippet I didn't found the request for dialogs.

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
