### ISSUE TITLE
Call Issue when logged in a same user in multiple devices

### ISSUE THREAD

**Issue by sapkotamadhusudan** [ConnectyCube/android-messenger-app#66]
I've installed the the android-messenger-app in three device. and in two of the device i logged in with same user and with other one device i've logged in with other account and started the call.

devices: **deviceA**, **deviceB**, **deviceC**
users: X,Y

**deviceA** and **deviceB** is logged as X
**deviceC** is logged in as Y

when Y calls the user X, **deviceA** and **deviceB** receives the call and after i accepted the call from **deviceA**, 
no event is triggered in **deviceB** that same user accepted call from another device.
and also when **deviceB** rejects the after **deviceA** accepted, call will disconnected from both **deviceB**, and **deviceC**

i've looked into the react-native-connectycube sdk too, there was a event callback i.e
`Connectycube.videochat.onStopCallListener()`

Is there any alternative event callback in react-native-android sdk.

**Comment by TatankaConCube** [comment]
In Android SDK we have similar callbacks:
```kotlin
/**
 * Called in case when opponent has rejected your call
 */
override fun onCallRejectByUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}
```
and
```kotlin
/**
 * Called in case when opponent hung up
 */
override fun onReceiveHangUpFromUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}
```
More info you can found in our [documentation](https://developers.connectycube.com/android/videocalling?id=track-session-callbacks).

**Comment by sapkotamadhusudan** [comment]
@TatankaConCube thanks for the info, but i've tried using these events. I works for the call initiator i.e. **deviceC**. But in my case **deviceA** and **deviceB** and are opponents with same user logged in, and none of the following events are invoked to the **deviceB** after **deviceA** accepted or rejected the call.

`/**
 * Called in case when opponent has rejected your call
 */
override fun onCallRejectByUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}`

`/**
 * Called in case when opponent hung up
 */
override fun onReceiveHangUpFromUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}`

`/**
 * Called in case when opponent accept the call
 */
override fun onCallAcceptByUser(session: RTCSession, userId: Int, userInfo: MutableMap<String, String>?) {}`

**Comment by TatankaConCube** [comment]
As a variant you can organise additional signalling via [System messages](https://developers.connectycube.com/android/messaging?id=system-messages) feature. Oriented logic will be:
- **deviceA** sends system message for himself (**userX**) with parameter `self_action=accept` (`self_action=reject`, `self_action=hang_up` for another actions) and `type=self_signalling` when does **Accept call** (or another) action;
- **deviceB** receives this message and does needed actions (close call screen, etc.);

**Comment by sapkotamadhusudan** [comment]
@TatankaConCube Thank you very much. I did implemented the purposed solution, it worked :)
