### ISSUE TITLE
Session Expire

### ISSUE THREAD

**Issue by nigma-bit** [ConnectyCube/android-messenger-app#68]
Login using firebase project id and token, that is fine
after 2 hour .that session was expire and never renew 
how i have to handle this problem

**Comment by TatankaConCube** [comment]
@nigma-bit sorry for a long time answer
Please add more details about your issue: 
- do you use an internal [session manager](https://developers.connectycube.com/android/authentication-and-users?id=session-token-management)?
- add full log from logcat during getting this issue;

Additionally, you can use [SessionListener](https://developers.connectycube.com/android/authentication-and-users?id=session-token-management) to listen session state.
