### ISSUE TITLE
Could not resolve com.google.code.findbugs:jsr305:3.+.

### ISSUE THREAD

**Issue by oscarpeli** [ConnectyCube/android-messenger-app#69]
Hi there,
I've just downloaded the demo project and tried to compile but I get the following error:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:3.+.

I'm working on Android Studio 4.0.1

Can you help?

**Comment by TatankaConCube** [comment]
Hello @oscarpeli, please add more details, tow to reproduce this issue? Did you download .zip archive and open it as an existing android project? Or you cloned the project using Android Studio's instruments? Did you do any changes in the project (update Gradle, code modifications, etc)?

**Comment by oscarpeli** [comment]
Hello @TatankaConCube, yes I downloaded the .zip archive and open it as an existing android project; then I run 'Debug app'.
I did it many times and downloaded the source code more than once with the same effect.
OBVIOUSLY, now that I repeated the process once again ... IT WORKED!.
Sorry for your time, now it works even if I did the same things.
Best Regards

**Comment by TatankaConCube** [comment]
Can I close this ticket?

**Comment by oscarpeli** [comment]
Yes, Please.
Just a last question: is it possible to get some code samples in java?
