### ISSUE TITLE
ConnectycubeRestChatService.getChatDialogs() returns chats with photo as null

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#82]
ConnectycubeRestChatService.getChatDialogs() returns chats with photo as null even if photo is there.
I checked on dashboard with the chat id. Everything is matching except the photo. There is a photo url in the dashboard but am receiving photo=null

**Comment by jddeep** [comment]
@TatankaConCube please look into this

**Comment by TatankaConCube** [comment]
@jddeep please provide the log with uploading the avatar and with getting the dialogs. I have checked it right now and it works correctly on the app from the `master` branch. For which type of dialog do you change the photo?

**Comment by jddeep** [comment]
@TatankaConCube Private Chat dialogs.
Here is the code I am using for fetching the chats from server.
``` fun loadChats(): LiveData<ApiResponse<List<Chat>>> {
        val requestBuilder = RequestGetBuilder()
            .sortDesc(Consts.DIALOG_LAST_MESSAGE_DATE_SENT_FIELD_NAME)
            .`in`(Consts.DIALOG_TYPE, 2, 3)

        return InjectorUtils.provideConnectycubeServiceForType<ArrayList<ConnectycubeChatDialog>, List<Chat>>()
            .perform(
                ConnectycubeRestChatService.getChatDialogs(null, requestBuilder),
                object : Converter<List<Chat>, ArrayList<ConnectycubeChatDialog>>() {
                    override fun convertTo(response: ArrayList<ConnectycubeChatDialog>): List<Chat> {
                        Log.e("FetchedChats: ", response.toString())
                        return convertToChats(response)
                    }
                })
    }

**Comment by jddeep** [comment]
@TatankaConCube I checked on the admin dashboard of the chat dialogs, the photo urls are there. Which means the uploading is correct.

**Comment by TatankaConCube** [comment]
Please provide the logs which contain both requests, update and get dialogs without any filters.

> For which type of dialog do you change the photo?

?

**Comment by jddeep** [comment]
@TatankaConCube ConnectycubeDialogType.PRIVATE

**Comment by TatankaConCube** [comment]
You provided part only with private dialogs. I think the server fills this field dynamically by setting the opponent's photo there, but I'm not sure, need to consult with the backend team. I will back later.

**Comment by jddeep** [comment]
Let me know if that's the case. Cause while signing up a user we are not providing a photo at that time.

**Comment by TatankaConCube** [comment]
Yes, I was right, server gets data from field 'avatar' of opponent and sets it as a 'photo' for private dialog.

**Comment by jddeep** [comment]
@TatankaConCube okay. Then you are suggesting adding the avatar while signing up the user/opponent? In that way the chat dialog will have the photo?

**Comment by jddeep** [comment]
@TatankaConCube By the way, this is how we are creating the chat dialog:

```
val array = arrayOfNulls<ConnectycubeUser>(liveSelectedUsers.value!!.size)
        liveSelectedUsers.value?.toArray(array)
        val chatDialog: ConnectycubeChatDialog = DialogUtils.buildDialog(*array)
        name?.let { chatDialog.name = name }
        avatar?.let { chatDialog.photo = avatar }
        return Transformations.map(
            chatRepo.createChatDialog(
                convertToChat(chatDialog).apply {
                    this.name = chatDialog.name ?: (array[0]?.fullName ?: "")
                    this.photo = chatDialog.photo ?: (array[0]?.avatar ?: "")
                }
            )
        )
```
And the `avatar` here is a valid image url and it is getting stored in the `photo` field of the dialog as can been seen in the admin dashboard. Wonder still why its dynamically changed to `null` while fetching

**Comment by TatankaConCube** [comment]
No, you have to set the 'avatar' for user, not for dialog. In this way server will return photo.

**Comment by jddeep** [comment]
Okay let us try that. Will let you know

**Comment by jddeep** [comment]
@TatankaConCube Apparently its working! Thanks for the help.
