### ISSUE TITLE
Query redarding Connecty Cube user Ids

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#84]
So currently a connecty cube user Id has 6/7 digits. I wanted to know about the case when the number of combinations finishes.
What happens then? Would there be redundant Ids of past users assigned to new users?

**Comment by jddeep** [comment]
@TatankaConCube any leads?

**Comment by TatankaConCube** [comment]
no, there will not users with the same ids.

**Comment by jddeep** [comment]
so however large the user base is, user ids will be different for different users ALWAYS ?

**Comment by TatankaConCube** [comment]
yes
