### ISSUE TITLE
Audio echo while Video call

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#86]
There is a great echo of voices during a video call between 2 people

**Comment by jddeep** [comment]
@TatankaConCube please have a look

**Comment by TatankaConCube** [comment]
how do you reproduce this issue? Are devices placed near each other or far? Which devices do you use for reproducing this issue?

**Comment by jddeep** [comment]
This is fixed for now. Will let you know if we face this again.
