### ISSUE TITLE
Random string instead of user name in chat push notification

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#89]
This happens while the opponent sends a message for the first time.

![WhatsApp Image 2021-05-10 at 15 06 31](https://user-images.githubusercontent.com/43133646/117639915-1203f680-b1a2-11eb-840e-d69b8dc23c3e.jpeg)

**Comment by jddeep** [comment]
@TatankaConCube Please have a look at this

**Comment by TatankaConCube** [comment]
@jddeep as you can see from code:
```kotlin
        val dialog: Chat? = chtRepository.getChatSync(dialogId!!)
        val dialogName = dialog?.name ?: dialogId
```
you will see `dialogId` if you don't have a dialog with `dialogId` in your local DB. So it is expected behavior.

**Comment by jddeep** [comment]
@TatankaConCube Any suggestions to how to fix this at all?

**Comment by jddeep** [comment]
@TatankaConCube any leads?

**Comment by TatankaConCube** [comment]
you can request the dialog from the server, but it takes some time and you will show notification with some delay.
