### ISSUE TITLE
Empty Chat dialog is created even though user doesn't sends messages

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#90]
This creates confusion and redundant items in chat list screen. Is there a way to not show such items in this list?

**Comment by jddeep** [comment]
@TatankaConCube

**Comment by TatankaConCube** [comment]
@jddeep please add more detail how we can reproduce it on our sample or add logs from starting the app till getting this issue and detailed steps how you reproduce it.

**Comment by jddeep** [comment]
I was able to fix this from the frontend side. Thanks
