### ISSUE TITLE
Messages Missing in Chat screen

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#91]
Is there a limit of messages which are shown on the chat screen after certain number limit?

**Comment by jddeep** [comment]
@TatankaConCube Please take a look

**Comment by TatankaConCube** [comment]
No, we don't have any limits for the chat history. Please add more details about your issue. Which is the actual result and what is the expected result.

**Comment by jddeep** [comment]
So in the ConnectyCube dashboard for a chat dialog we can see there are around 50 chat messages..but in app in the chat message screen only last 20 comes. The numbers I have taken are just to show example but something like this is happening even after clear data and login.

**Comment by jddeep** [comment]
@TatankaConCube

**Comment by TatankaConCube** [comment]
can you please provide the logs with the scrolling the messages list. According to the code, there should be pagination logic and during scroll, the app should load messages by pages 20 items per page.

**Comment by jddeep** [comment]
is there a page limit set anywhere in the code? @TatankaConCube

**Comment by TatankaConCube** [comment]
sure, you can found it in code [there](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/data/ChatMessageRepository.kt#L194)
