### ISSUE TITLE
Base Forbidden. Need User after coming back to background app after app update

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#94]
Base Forbidden. Need User after coming back to background app after app update

**Comment by jddeep** [comment]
@TatankaConCube Please take a look into this

**Comment by TatankaConCube** [comment]
@jddeep  please add more details, what you do and how you get this error. Please attach the logs from the logcat console.

**Comment by jddeep** [comment]
We had found a work around
