### ISSUE TITLE
ConnectyCube resets or deletes the user FCM Token from Firebase Messaging as well for the device after unsubscribe from pushes

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#98]
`SubscribeService.unSubscribeFromPushes(applicationContext)`

This is the line which is responsible for this. After uncommenting this the fcm token is survived even after logout and doesn't change for the user which is what we want.

**Comment by jddeep** [comment]
@TatankaConCube Please take a look here

**Comment by TatankaConCube** [comment]
@jddeep  could you please provide the log after calling the `SubscribeService.unSubscribeFromPushes(applicationContext)`. Do you have any errors there?
What unexpected behavior do you get with this issue? Why do you need the new token after unsubscription?

**Comment by jddeep** [comment]
@TatankaConCube No there are no errors. All the process works good.
We don't need new token. We want old token only.
The issue is this line of code changes destroys the old token and a new token is generated by firebase messaging after re login.
We removed the line and checked and everything was fine. The old token was reserved.

**Comment by TatankaConCube** [comment]
within SDK we call `instanceID.deleteToken(senderId, FirebaseMessaging.INSTANCE_ID_SCOPE);` and clean your data related to FCM, just FYI

**Comment by jddeep** [comment]
Well that is exactly what's causing this @TatankaConCube ! Can you tell why exactly are you doing this? And other than this what all things are you doing under the hood while unsubscribing

**Comment by TatankaConCube** [comment]
in my preview comment, I said, what we do while calling `SubscribeService.unSubscribeFromPushes(applicationContext)`

> why exactly are you doing this

we do this for stopping receiving push notifications in the app.

But you can realize own logic for unsubscribing from push notifications, for this, you have to save the subscription id and use it for deleting subscription via our API:
```java
ConnectycubePushNotifications.deleteSubscription(subscriptionId);
```

**Comment by jddeep** [comment]
Closing this for now
